package com.example.pintly

import androidx.annotation.ColorRes

/**
 * A single category of prompts ("tiles"). [weight] controls how often the category
 * is drawn relative to the others; [info] is the explanation shown by the ⓘ badge.
 */
data class Category(
    val name: String,
    @ColorRes val colorRes: Int,
    val weight: Int,
    val info: String,
    val prompts: List<String>
)

/**
 * All of Pintley's game content. Prompts are preserved verbatim from the original
 * 2023 build. "Player X/Y/Z" placeholders are substituted with real player names at
 * runtime (see [MainActivity]).
 */
object GameData {

    fun categories(): List<Category> = listOf(
        Category(
            name = "Regular",
            colorRes = R.color.LightPurple,
            weight = 55,
            info = "If no one is named, ask everyone the question",
            prompts = listOf(
                "Take a drink if you have ever crashed your car",
                "Take a drink for every book you read this year. If you answer 0, down your drink - illiterate",
                "Player X share a lie that you told someone in the group and they believed, if you can't then drink 2",
                "Take a drink if you have slept with someone in the group, don't explain",
                "Whoever is the least drunk, drink 3",
                "Everyone takes a drink",
                "Take a sip for every country you have visited",
                "Player X, make older players drink 2, if you are the oldest drink 3 for being such a creep",
                "Player X, make younger players drink 2, if you are the youngest drink 3 and blink twice for help",
                "Player X, the group asks you one question, if you don't want to answer drink a shot",
                "Player X, choose a category (eg cars), if someone can't continue the category within 5 seconds they drink 3",
                "Player X, take 2 drinks",
                "All women drink 1, if there's no women here everyone drinks 2 in shame",
                "Person with the largest feet drinks 2",
                "Player X, anyone with the same first letter drinks 1, yes that includes you",
                "Player X, give out 2 drinks to whoever you choose",
                "Person closest to the door drinks 2",
                "Everyone take 2 drinks, if your drink has ice in it take 4 for being precious",
                "People in a relationship, drink 2",
                "Drink if you haven't been to the gym in the last month, drink double if you have a membership",
                "Drink for each streaming service you are subscribed to",
                "If you are romantically interested in someone here, take a drink but don't explain yourself",
                "If you are under 6'0 drink 2 in shame, manlet",
                "Drink 3 if you have ever complained about food at a restaurant",
                "Player X, give out as many drinks as first names you have",
                "BOOM! Player X down your drink!",
                "Drink 3 if you have given an excuse to why you won't drink today",
                "Drink 2 times if you can't sleep after sex, virgins drink 3 in sadness",
                "Women drink your bra size, A = 1, B = 2, etc",
                "Drink 2 if you have said I love you in the last 24 hours",
                "Drink 3 if you have ever painted your nails",
                "Men, 1 drink per inch. Please lie for God's sake",
                "Everyone take a drink for each piece of black clothing you are wearing, very boring",
                "Player X, give out 3 sips to a player smaller than you, if you can't - drink them!",
                "If you have beautiful hair, drink 3",
                "If you have short hair, drink 2 drinks",
                "If you have blond hair, give out 3 drinks",
                "Most highly educated drinks 2, know it all",
                "Drink 2 if you have ever shoplifted",
                "Drink 1 if you can play an instrument",
                "Drink 1 if you drove here",
                "Drink 1 if you've been on a bus in the last month",
                "The last person who drank, drink that amount again",
                "Whoever knows the least people here drinks",
                "The host drinks, round of applause please",
                "Whoever lives furthest from here, drinks 2",
                "Whoever poured their drink longest ago, finally finish it off",
                "Player X take 3 drinks of Player Y's drink",
                "Drink once for each blue eye",
                "Papers please! Drink 1 if you don't have ID on you",
                "Anyone under 5'6 or with a beard, drink 3 like a true dwarf! 6 if both",
                "Whoever has met the most famous person gives out 4 sips",
                "Person with the most photos on their phone drinks 1",
                "Whoever's phone this is, give out 5 drinks for supporting my app :)",
                "Anyone wearing a watch, take 1 drink",
                "Everyone with a Samsung drink 1",
                "Drink 2 if you shaved today",
                "Player X what's the name of the song and artist playing right now. Drink 3 if you are incorrect",
                "Those who drank for the previous tile, drink again",
                "Everyone take as many sips as you studied after school",
                "Player X, give out 3 drinks to a player who is less drunk than you - if its impossible down 6 drinks",
                "Player X, if you are wearing clothes you bought this month, take 3 drinks",
                "Player X, if you don't have Player Y then you can both drink 1",
                "If you believe in ghosts, drink 3",
                "If you have studied more than Player X, drink 2",
                "Drink 2 if you've slept with someone in the room. Drink 5 if you feel the need to explain",
                "Largest player, give out 2 sips",
                "Drink 1 if you have ever skinny dipped",
                "Take a drink if you have ever eaten an insect",
                "Take a drink if you \"Don't dance\"",
                "Take 2 drinks if you are unemployed, 4 if you have been for over a year",
                "Take 2 drinks if you have had a celebrity encounter",
                "Player X, drink 3 drinks if you have ever gone to a costume party",
                "Player X, take 3 drink if you have never been to a casino. Very boring!",
                "If you think you can dance, give out 2 drinks",
                "Take 2 drinks if you have never been in a fight",
                "Take 1 drink if you have ever played twister, 3 if it was sexy twister",
                "Give out 1 shot if you rated this app 5 stars, I love you",
                "Give out 2 drinks if you usually play a sport, take 4 if you're bad at it",
                "Take 2 drinks if you have ever used a dating app, honestly that's depressing",
                "Give 2 drinks if you have been to a music festival",
                "Player X, donate a shot if you have volunteered for a charity",
                "Drink 3 if you're a virgin, double it if you study computer science",
                "Bodybuilders drink 3, you can take it",
                "Player X, if you can touch your nose with your tongue, give out 2",
                "Player X take a drink for every social media app on your phone",
                "Drink 1 if you have had a sexual fantasy about someone in the room. Don't explain",
                "Player X, drink 2 if you lied on your resume",
                "If you arrived alone drink 1. If you think you'll leave alone, drink 2",
                "If you know what League of Legends is, drink 2",
                "Player X, name a TV show. Whoever has seen it drink 1",
                "Drink 1 if you have signed a petition this year",
                "Drink 1 if you like pineapple on pizza",
                "Drink 2 if you ever tried to stream on twitch",
                "Drink 1 if you don't want kids, give out 2 drinks if you do",
                "Player X, name a movie. Whoever has seen it drink 1",
                "Give out 3 drinks if you have ever been arrested",
                "Give out 2 drinks if you have hugged a dangerous animal such as a lion or tiger",
                "Drink 2 if you have more than 5 GCSEs (or equivalent)",
                "Player X drink for every tattoo you have, if you have none then give out 2 drinks",
                "Drink 3 if you have slept with an ex, double it if it's a friends ex",
                "If you are over 18 and still use snapchat take a drink",
                "Drink 2 if you shared your spotify wrapped this year",
                "Player X, Player Y and Player Z drink 3 if you skipped leg day this week (or didn't go)",
                "Give out as many drinks as nights you've been drinking in a row",
                "Drink 1 if you said \"No we can't!\" to Bob the Builder",
                "Give out 3 drinks if you have ever been physically escorted out of a venue",
                "Introverts take 2 drinks",
                "Extroverts give out 2 drinks",
                "If you ever used Kik, drink 2 for your emotional scars",
                "Player X, drink 1  every tiktok you have been a part of (maximum 10 drinks)"
            )
        ),
        Category(
            name = "Action",
            colorRes = R.color.LightRed,
            weight = 20,
            info = "This is a task for whoever is named",
            prompts = listOf(
                "Player X, state some advice you want to give to someone in the group, don't ask who - or drink 2",
                "Player X, name your biggest turn-off or drink 3",
                "Player X, you now control the music, drink 1 if the group hears a bad song",
                "FREEZE. Player X throw a coin from where they are, if it lands in someone's cup they must down it",
                "FREEZE. Person with the least in their drink, finishes it off",
                "Whoever is the least drunk, the group decides how much you drink",
                "Player X, choose another player, decide how much you both drink",
                "Player X, choose something you have never ever done, if someone has done it they must drink",
                "Last person to bring up a photo of another player on their phone must drink 4",
                "Player X, choose a rhyme, go round clockwise and the last person to think of a rhyme must drink 3",
                "Player X, pour a shot into another player's drink",
                "Player X, tell another player a heartfelt compliment, the group will judge if you drink 3 or not",
                "Player X, play two truths and a lie, if no one guesses the lie they all drink 2",
                "Long arm pint! Player X finish your drink without bending your elbow",
                "Everyone play rock paper scissors with the person to your left, overall winner gives out 5 drinks",
                "Player X, make a rousing speech to the other players, after which they communally decide how much you drink",
                "Player X, imitate Player Y, yes that includes their drinks",
                "Take a group selfie to remember the moment, anyone that refuses drinks 3",
                "Everyone puts a hand on the table, the last person to take their hand off gives out 5 sips",
                "Player X, take a shot like a hero, or give out two shots like a villain",
                "Player X, take an item of clothing from each player (e.g., hat), if you refuse drink 3",
                "First person to recite the alphabet backwards gives out 5 drinks",
                "Everyone puts their phone in the middle, first to get a notification drinks 3",
                "Player X, give your phone to the person to the left, they write a text to someone. If you choose not to send it, drink 5",
                "Take a drink if you have ever drank in a park, you menace",
                "Say 'On My Ship Is' and add an item. Each player must repeat and add a new item. Whoever messes up drinks 1 for each item mentioned",
                "Everyone stops speaking! Everyone must drink in alphabetical order. If you mess up then restart",
                "Player X, speak about a subject for a minute, you cannot repeat words. Every time you do, take a drink",
                "Take a drink for every drug you've ever tried, we're judging you",
                "Choose an object in the room, last to touch it drinks 3",
                "Player X, tell an embarrassing story or drink 3",
                "The first person to come up with an inspirational quote gives out 4 sips",
                "Player X must stand on one leg until told otherwise, drink 1 for messing up",
                "Player X, make a show of athleticism (e.g., push-ups) or drink 5",
                "Player X names a band, Player Y must name 5 of their songs or you both drink 5 instead",
                "Player X, choose another player for a staring contest, loser drinks 3",
                "Player X, come up with a dare for Player Y, if they refuse they drink 4",
                "Player X, choose a song and sing 30 seconds of karaoke or drink 2",
                "Stand up! Last player to do so drinks 2",
                "STOP TALKING! Player X must state what Player Y last said or drink 2",
                "Play hide and seek! Player X seeks, first to be found drinks 2, last to be found gives 2",
                "Player X must do a 30-second interpretive dance of whatever Player Y is saying",
                "Go round in a circle rhyming with a word Player X chooses, first to mess up drinks 3",
                "Player X, sing your national anthem, if it's not passionate enough drink 3",
                "Player X hums a tune for 5 seconds, if Player Y can't get it you both drink 4",
                "On the count of 3 raise your hand, anyone with the same number of fingers as anyone else drinks 2",
                "Player X, explain to the group why you shouldn't drink 5 immediately",
                "Player X, assign eye colors to drink 1, 2, or 3 drinks",
                "Player X, take 6 sips out of your glass or 1 sip out of your bare palm",
                "Player X, please refill your glass without using your hands",
                "Player X and Player Y make competing toasts, the worst voted toast drinks 2 and the best gives 2",
                "Player X, come out with a catchphrase you must say everytime you drink",
                "Player X, choose someone to do 20 push ups",
                "Player X, choose someone to do 30 squats",
                "Player X, please refill your glass without using your hands",
                "All players please bid on the right to give out 6 drinks, bids start at 2 drinks",
                "Everyone read out your last social media post - if you refuse drink 2",
                "Go round and list bars/clubs you've been to. Those who mess up drink 2",
                "Player X, imitate a scene from a movie in silence. First to guess the movie gives out 3 drinks",
                "Go round and list bars/clubs you've been to. Those who mess up drink 2",
                "Player X, tell a joke. If anyone laughs they drink 2",
                "Player X, tell a story and the group decides if you drink 3 or not",
                "Player X, please pour a shot into two other players drinks",
                "Player X, reveal your truest phobia or take a shot",
                "Player X pour Player Y's next drink",
                "Every 20 minutes (eg 8:00, 8:20, 8:40) the first player to say \"Pintley\" gives out 5 drinks",
                "Couples think back to your last argument. Whoever was in the wrong, drink 5 in shame",
                "Whoever removes a piece of clothing first, give out 2 dip drinks",
                "Player X, close your eyes and say what everyone is drinking. Give out 1 drink per correct answer, if you mess up drink them",
                "Player X, name as many African capitals as you can. Give out 1 drink per answer but if you mess up, drink them",
                "Player X, name as many Asian capitals as you can. Give out 1 drink per answer but if you mess up, drink them",
                "Player X, name as many South American capitals as you can. Give out 1 drink per answer but if you mess up, drink them",
                "Player X, name an accessory. Whoever is wearing that accessory drinks 1",
                "Player X drinks for 5 second Player Y does the counting",
                "Drink 1 if you're a summer person",
                "Drink 1 if you're a winter person",
                "If you are wearing a hat, doth it at another player and they must drink 2",
                "Left handed people drink 1, ambidexturous people dual wield two drinks and drink them both",
                "Everyone says a pickup line, corniest and none-participants drink 1",
                "Player X, do an impression of Player Y. The group can give out 3 drinks based on the quality",
                "Player X tell us about the time you did or almost shit yourself. Take a shot instead if you're a coward",
                "Player X drink the total of your bodycount",
                "Player X let another player modify your tindr or take 2 shots. If you don't have one, give out 1 shot",
                "Player X must be Player Y's cheerleader everytime they take a drink, motivate them to drink more",
                "Player X, tell an offensive joke. If it's not judged offensive enough, drink 4"
            )
        ),
        Category(
            name = "Rule",
            colorRes = R.color.Gold,
            weight = 4,
            info = "Rules effect everyone and stay in place until stated otherwise",
            prompts = listOf(
                "No eye contact, if anyone happens to make eye contact you both drink 1",
                "If anyone makes eye contact, the first to wink makes the other drink 1",
                "Player X, decide on new names for everyone, if someone messes up they must drink",
                "Player X, replace a word of your choice with another word, if anyone uses the old word they drink 1",
                "No one can cross their legs or touch their hair. If anyone sees you do it, you drink 1",
                "Left Hand Rule! Players must hold their drink with their none dominant hand. Drink 1 if you mess up",
                "Each time you refer to a player, everyone must use a different name. Drink 1 if you mess up",
                "Player X, Player Y and Player Z are all a team. The team majority chooses how to divide their drinks",
                "Everyone is Question-Master! If anyone answers someone elses question then they drink 1",
                "All players swap names! Decide who is who and if anyone uses the old name they drink 1",
                "Whenever a player drinks they must choose either the person to their left or right to drink with them"
            )
        ),
        Category(
            name = "Weakness",
            colorRes = R.color.SicklyGreen,
            weight = 4,
            info = "This is a penalty that a single player holds until stated otherwise",
            prompts = listOf(
                "Player X, if you say someone's name, take a drink and they get to write their name on your skin",
                "Player X must call everyone by their full name, every time you fail drink 1",
                "Player X, choose a small item to protect, if anyone obtains it then you must drink 4",
                "Player X is a drink bitch, you must make a drink for anyone that asks you",
                "Questions only, if Player X makes a statement that isn't a question, they must take a drink",
                "Player X is feeling a bit slow, if you use any conjunctions (and, but, there, while) take a drink",
                "Player X, all your drinks are doubled, sorry",
                "Player X may only use your index fingers to drink, no spilling!",
                "Player X, swap drinks with Player Y",
                "Player X, you are an aristocrat, raise your pinky whenever you drink or drink again",
                "Player X is in court, speak only through whispering to your lawyers sitting to your left and right",
                "Player X must do an impression of their choice, each time they mess up they drink 2",
                "Player X must end all sentences with \"is that okay!?\" or take a drink",
                "Player X, use your least dominant hand to drink, if you mess up drink 1",
                "Player X, you must raise your hand to speak, if you mess up drink 1",
                "Player X this is a serious matter. Make a serious face, if you break it or laugh, drink 1",
                "Player X must end all sentences with \"is that okay!?\" or take a drink",
                "Player X, use your least dominant hand to drink, if you mess up drink 1",
                "Player X, you must raise your hand to speak, if you mess up drink 1",
                "Player X, is down with the kids. Speak only in outdated slang, ya dig",
                "Player X, you must say the opposite of what you mean to say",
                "Player X, speak only in Ye Olde English, drink 1 if you mess up",
                "Player X, you must answer all questions asked truthfully, as if you were Player Y"
            )
        ),
        Category(
            name = "Special",
            colorRes = R.color.Violet,
            weight = 3,
            info = "A player may use this once, whenever they want",
            prompts = listOf(
                "Player X, reflect any drinks you are given, one time",
                "Player X, give away a single weakness to another player of your choice",
                "Player X, raise your hands in the air. The last person to raise their hands drinks 3",
                "Player X, touch your thumb to the table. The last person to also touch their thumb to the table drinks 3",
                "Player X, change the player named on another tile",
                "Player X, choose to bring a rule back from the graveyard"
            )
        ),
        Category(
            name = "Wild",
            colorRes = R.color.ForestGreen,
            weight = 1,
            info = "These are up to you, have some fun",
            prompts = listOf(
                "Player X, decide what this tile says",
                "Player X, decide what this tile says",
                "Player X, decide what this tile says",
                "Player X, choose a democracy question",
                "Player X, choose a democracy question",
                "Player X, choose a democracy question",
                "Player X, decide on a rule",
                "Player X, decide on a rule",
                "Player X, decide on a rule"
            )
        ),
        Category(
            name = "Democracy",
            colorRes = R.color.LightBlue,
            weight = 15,
            info = "Everyone close your eyes and point to who you think the answer is, players in the minority drink",
            prompts = listOf(
                "Who is the best dressed?",
                "Who is the worst driver?",
                "Who is the biggest lightweight?",
                "Who is the biggest alcoholic?",
                "Who here is the least drunk?",
                "Who here is the most fun?",
                "Who here is the strongest?",
                "Who here will be the most successful in life?",
                "Who here is the most privileged?",
                "Who here is the biggest social butterfly?",
                "Who would you rather be stranded on a deserted island with?",
                "Who would you call to hide a body?",
                "Who would you rather wake up as?",
                "Who would make the best politician?",
                "Who is the worst cook?",
                "Who is the most likely to ditch on your plans last minute?",
                "Who is going to throw up first?",
                "Who is going to bed soon?",
                "Who is worst at handling spice?",
                "Who is the least dominant?",
                "Who is the horniest?",
                "Who is wearing the most expensive clothes?",
                "Who is the most sensitive, oh no?",
                "Who has the worst taste in music?",
                "Who has the best taste in music?",
                "Who was the most popular in school?",
                "Who has the highest 'body count'?",
                "Who has the weakest drink?",
                "Who has the strongest drink?",
                "Who is the most athletic?",
                "Who is the best gamer?",
                "Who has the strangest hobby?",
                "Who has the best taste in TV/Movies?",
                "Who is the least hygienic?",
                "Who is the worst loser?",
                "Who is the least employable?",
                "Who do you trust the most?",
                "Who would you want in a fight?",
                "Who is most likely to complain?",
                "Who is the biggest bullshitter?",
                "Who is the most gullible?",
                "Who is the biggest nerd?",
                "Who is the best on a night out?",
                "Who is the most dramatic?",
                "Who is least likely to get into a club?",
                "Who is most likely to 'forget' to buy a round?",
                "Choose who would win in a fight, Player X or Player Y",
                "Who is the loudest?",
                "Who is the most confrontational?",
                "Who has the hardest job?",
                "Who is the most persuasive?",
                "Who is the best tipper?",
                "Who is most likely to complain at a restaurant?",
                "Who is the most adventurous?",
                "Who would you least like to live with?",
                "Who is most likely to go to sleep first?",
                "Who is the worst in bed?",
                "Who would make the best warrior?",
                "Who would make the best king?",
                "Who is the most promiscuous?",
                "Who is the life of the party?",
                "Who would you want most in a zombie apocalypse?",
                "Who would you want as your partner in your fortune 500 company?",
                "Who gives the best advice?",
                "Who gives the worst advice?",
                "Who is the most knowledgeable about pop culture?",
                "Who is the most cultured?",
                "Who is the best at keeping a secret?",
                "Who is the biggest risk taker?",
                "Who is the most aggressive?",
                "Who will be the first to start a family?",
                "Who is the drunkest?",
                "Who would perform best in the military?",
                "Who is the most practical?",
                "Who is the coolest?",
                "Who is the groups main organiser?",
                "Who is your role model?",
                "Who would you want as your negotiator in a hostage situation?",
                "Who would you most like to investigate your murder?",
                "Whose facts do you trust the most without conformation?",
                "Who do you want as your partner in a horror movie?",
                "Who is your chosen heist-partner?",
                "Who is your chosen prison friend?",
                "Who would do the best in prison?",
                "Who is the most likely to be guilty of a crime?",
                "Who here will people write books about?",
                "Who is most likely to join an extremist group?",
                "Who is most likely to be successful in staging a revolution?",
                "Who should really speak less?",
                "Who should really speak more?",
                "Who do you trust most to speak on your behalf?",
                "Who do you trust least to speak on your behalf?",
                "Who is the happiest in the room right now?",
                "Who is the best storyteller?",
                "Who is the most passionate?",
                "Who do you trust least to plan a holiday?",
                "Who is always causing drama?",
                "Who is the most resilient?",
                "Who is the most optimistic?",
                "Who is the meanest?",
                "Who would make the best supervillain?",
                "Who has the best relationship with their parent(s)?",
                "Who is the shotcaller?",
                "Who is the worst swimmer?",
                "Who is the parent of the group?",
                "Who would go the furthest to help you?",
                "Who is the most elitist?"
            )
        ),
        Category(
            name = "Power",
            colorRes = R.color.CrimsonRed,
            weight = 4,
            info = "This is a benefit that a single player holds until stated otherwise",
            prompts = listOf(
                "Player X, choose a friend, whenever you drink they drink",
                "Player X, you are the group's boss. Inappropriate workplace conduct must be punished with drinks.",
                "Player X, others must ask your permission before having a drink, if they forget they drink double",
                "Player X is a concerned father, all players must refer to you as daddy. Mess up and drink 1",
                "Player X is Question-Master, anyone who answers any of your questions must drink 1",
                "Player X is Passion-Master, you can assign 1 drink to anyone not showing enough passion for the night",
                "Player X, whenever you make two finger guns, everyone must freeze. The last to do so drinks 2",
                "Player X is a symbol monkey, everytime they clap their hands everyone drinks 1 including themselves",
                "Player X is question-master, anyone who answers any of your questions must drink 1",
                "Player X, whenever you make a person laugh they must now drink 1",
                "Player X is immune to the effects of rules",
                "Player X is immune to the next 5 tiles, Player Y must drink them instead"
            )
        ),
        Category(
            name = "Elimination",
            colorRes = R.color.Granite,
            weight = 2,
            info = "Remove something from play. We recommend doing this freely rather than using the prompts",
            prompts = listOf(
                "All Rules are out of play",
                "All Powers are out of play",
                "All Weaknesses are out of play",
                "All Rules/Powers/Weaknesses are out of play",
                "All Rules are out of play",
                "All Powers are out of play",
                "All Weaknesses are out of play",
                "All Rules/Powers/Weaknesses are out of play",
                "All Rules are out of play",
                "All Powers are out of play",
                "All Weaknesses are out of play",
                "All Rules/Powers/Weaknesses are out of play"
            )
        ),
        Category(
            name = "Would You Rather",
            colorRes = R.color.Flamingo,
            weight = 6,
            info = "Everyone close your eyes. Thumbs up for Option 1, thumbs down for Option 2. The minority drinks",
            prompts = listOf(
                "Would you rather live agelessly for 100 years or receive a billion dollars?",
                "Would you rather the ability to breath underwater or the ability to fall from any height?",
                "Would you rather receive a life sentence or the death penalty?",
                "Would you rather only eat sweet food or only eat spicy food?",
                "Would you rather live without social media or without streaming services?",
                "Would you rather have permanent free travel or a super car?",
                "Would you rather be the richest person in the world and hated or broke but loved?",
                "Would you rather have street smarts or book smarts?",
                "Would you rather have permanent summer or permanent winter?",
                "Would you rather be reincarnated with your past memories and no skill or skills but no memory?",
                "Would you rather have immortality or reincarnation with intact memory?",
                "Would you rather eat the same meal forever or only be able to drink water?",
                "Would you rather be able to lift a car but look super weak or have the body of a Greek God but be moderate in strength?",
                "Would you rather have a million dollars or a 50% chance of 20 million dollars?",
                "Would you rather lose your hearing or lose your eyesight?",
                "Would you rather save 10 random people but sacrifice yourself or sacrifice 10 and save yourself?",
                "Would you rather have an amazing house or amazing holidays?",
                "Would you rather lie for a cheating friend or snitch on a cheating friend?",
                "Would you rather be the strongest man in the world by far or be the best at chess in the world by far?",
                "Would you rather be a perfect artist or a perfect mathematician?",
                "Would you rather have only one pet or only one child?",
                "Would you rather have the hottest partner or the smartest partner?",
                "Would you rather go into witness protection and never see your family or have 100 kids right now?",
                "Would you rather be able to control water or be able to control fire?",
                "Would you rather be permanently bald or have werewolf hair growth?",
                "Would you rather only watch movies or only listen to movies?",
                "Would you rather always be an hour late or 2 hours early?",
                "Would you rather read people's thoughts or read people's memories?",
                "Would you rather be unable to listen to new music or be unable to relisten to music?",
                "Would you rather find true love but never find work or have a successful career without ever finding love?",
                "Would you rather live in the Sahara Desert or Antarctica?",
                "Would you rather be able to code like a genius or play an instrument like a genius?",
                "Would you rather be ghosted by your crush or told you aren't liked by your crush?",
                "Would you rather be unable to shower or unable to brush your teeth?",
                "Would you rather know how you will die or when you will die?",
                "Would you rather have a personal chef or have a personal driver?",
                "Would you rather have two extra arms or have a third eye?",
                "Would you rather never break anything or never lose anything?",
                "Would you rather be smart but everyone depends on you or be stupid but completely taken care of?",
                "Would you rather choose where you go for dinner or have someone else choose?",
                "Would you rather have a great memory be a comedic genius?",
                "Would you rather date someone similar to you or different to you?",
                "Would you rather live in a world without war or live in a world without poverty?",
                "Would you rather live underwater or in space?",
                "Would you rather never have to sleep or never get sick?",
                "Would you rather be able to talk to animals all speak all languages fluently?",
                "Would you rather move objects with your mind or have super speed?",
                "Would you rather be immune to alcohol or be immune to recreational drugs?",
                "Would you rather have everyone respect you or desire you?",
                "Would you rather be a dog or a cat?",
                "Would you rather have a photographic memory or forget anything at will?",
                "Would you rather win the lottery or find true love?",
                "Would you rather be a lightweight or a heavyweight drinker?",
                "Would you rather have a world ruled by passion or logic?",
                "Would you rather own a 5 star hotel or a 3 michelin star restaurant?",
                "Would you rather swim 10 meters in 50°C or crawl 10 meters across burning coals?",
                "Would you rather be the best fighter in the world or the quickest reader?",
                "Would you rather sleep with Player X or Player Y?",
                "Would you rather earn double the money or work half as much for the same pay?",
                "Would you rather live in the current day as a regular person or 100 years ago as royalty?",
                "Would you rather be known as a prostitute or a fraudster who targets the elderly?",
                "Would you rather start your business empire with Player X or Player Y?",
                "Would you rather be Prime Minister or their most trusted advisor?",
                "Would you rather travel 40 years into the past or future?",
                "Would you rather have sex in the shower or the back of a car?",
                "Would you rather kill one person to save three, or not kill anyone and let three die?",
                "Would you rather not cheat on your partner but have them think you did or cheat on them but they think you didn't?",
                "Would you rather be addicted to cocaine or gambling?",
                "Would you rather fight like Mike Tyson or Bruce Lee?",
                "Would you rather serve in Heaven or rule in Hell"
            )
        )
    )
}
