package com.example.pintly

import androidx.annotation.ColorRes

/**
 * A single category of prompts ("tiles"). [defaultWeight] is the category's default
 * share (roughly a percentage; all defaults sum to 100). [info] is the explanation
 * shown by the ⓘ badge. The player can override enabled/weight in Category settings.
 */
data class Category(
    val name: String,
    @ColorRes val colorRes: Int,
    val defaultWeight: Int,
    val info: String,
    val prompts: List<String>,
    /** Ultra categories are drawn on a separate rare roll, not the weighted pool. */
    val isUltra: Boolean = false
)

/**
 * All of Pintley's game content. "Player X/Y/Z" placeholders are substituted with
 * real player names at runtime (see [MainActivity]). Prompts are kept short so they
 * read at a glance on screen.
 */
object GameData {

    fun categories(): List<Category> = listOf(
        Category(
            name = "Regular",
            colorRes = R.color.LightPurple,
            defaultWeight = 47,
            info = "If no one is named, ask everyone the question",
            prompts = listOf(
                "Drink if you've ever crashed your car",
                "Drink for every book you've read this year. Read none? Down your drink, illiterate",
                "Player X, share a lie you told the group that they believed. Can't? Drink 2",
                "Drink if you've slept with someone here. Don't explain",
                "Least drunk player, drink 3",
                "Everyone drinks",
                "Sip for every country you've visited",
                "Player X, older players drink 2. If you're the oldest, drink 3, creep",
                "Player X, younger players drink 2. If you're the youngest, drink 3 and blink twice for help",
                "Player X, the group asks you one question. Refuse to answer? Take a shot",
                "Player X, name a category (e.g. cars). First to stall for 5 seconds drinks 3",
                "Player X, drink 2",
                "All women drink 1. No women here? Everyone drinks 2 in shame",
                "Person with the biggest feet drinks 2",
                "Player X, anyone whose name starts with the same letter drinks 1 — you included",
                "Player X, give out 2 drinks",
                "Person closest to the door drinks 2",
                "Everyone drinks 2. Ice in your drink? Drink 4, precious",
                "Anyone in a relationship drinks 2",
                "Drink if you haven't hit the gym this month. Double if you pay for a membership",
                "Drink for each streaming service you pay for",
                "Drink if you fancy someone here. Don't explain",
                "Under 6 foot? Drink 2 in shame, manlet",
                "Drink 3 if you've ever sent food back at a restaurant",
                "Player X, give out a drink for each of your first names",
                "BOOM! Player X, down your drink!",
                "Drink 3 if you've made an excuse not to drink tonight",
                "Drink 2 if you can't sleep after sex. Virgins drink 3 in sadness",
                "Women, drink your bra size (A=1, B=2, C=3...)",
                "Drink 2 if you've said 'I love you' in the last 24 hours",
                "Drink 3 if you've ever painted your nails",
                "Men, 1 drink per inch. Please lie, for God's sake",
                "Drink for each black item you're wearing. Very boring",
                "Player X, give 3 sips to someone smaller than you. No one smaller? Drink them yourself",
                "Drink 3 if you have great hair",
                "Drink 2 if you have short hair",
                "Give out 3 drinks if you have blond hair",
                "Most educated player drinks 2, know-it-all",
                "Drink 2 if you've ever shoplifted",
                "Drink 1 if you can play an instrument",
                "Drink 1 if you drove here",
                "Drink 1 if you've been on a bus this month",
                "Last person who drank, drink that amount again",
                "Whoever knows the fewest people here drinks 2",
                "The host drinks. Round of applause, please",
                "Whoever lives furthest away drinks 2",
                "Whoever poured their drink longest ago, finish it",
                "Player X, take 3 sips of Player Y's drink",
                "Drink once for each blue eye in the room",
                "Papers please! Drink 1 if you don't have ID on you",
                "Under 5'6 or bearded? Drink 3 like a true dwarf. Both? Drink 6",
                "Whoever's met the most famous person gives out 4 sips",
                "Person with the most photos on their phone drinks 1",
                "Whoever's phone this is, give out 5 drinks for supporting the app :)",
                "Anyone wearing a watch drinks 1",
                "Everyone with a Samsung drinks 1",
                "Drink 2 if you shaved today",
                "Player X, name the song and artist playing right now. Wrong? Drink 3",
                "Everyone who drank on the last card, drink again",
                "Sip for each year you studied after school",
                "Player X, give 3 drinks to someone less drunk than you. No one? Down 6",
                "Player X, drink 3 if you're wearing something you bought this month",
                "Player X, pick someone you'd take on a road trip. You both drink 1",
                "Drink 3 if you believe in ghosts",
                "Drink 2 if you've studied more than Player X",
                "Drink 2 if you've slept with someone here. Drink 5 if you need to explain",
                "Biggest player, give out 2 sips",
                "Drink 1 if you've ever skinny dipped",
                "Drink if you've ever eaten an insect",
                "Drink if you 'don't dance'",
                "Drink 2 if you're unemployed. 4 if it's been over a year",
                "Drink 2 if you've met a celebrity",
                "Player X, drink 3 if you've been to a costume party",
                "Player X, drink 3 if you've never been to a casino. Boring!",
                "If you think you can dance, give out 2 drinks",
                "Drink 2 if you've never been in a fight",
                "Drink 1 if you've played Twister. 3 if it got sexy",
                "Give out a shot if you rated this app 5 stars. Love you",
                "Give 2 drinks if you play a sport. Drink 4 if you're bad at it",
                "Drink 2 if you've used a dating app. Bleak",
                "Give 2 drinks if you've been to a festival",
                "Player X, give out a shot if you've volunteered for charity",
                "Drink 3 if you're a virgin. Double it if you study computer science",
                "Bodybuilders drink 3, you can take it",
                "Player X, touch your nose with your tongue to give out 2",
                "Player X, drink for every social media app on your phone",
                "Drink 1 if you've fantasised about someone here. Don't explain",
                "Player X, drink 2 if you've lied on your CV",
                "Drink 1 if you arrived alone. Drink 2 if you'll leave alone",
                "Drink 2 if you know what League of Legends is",
                "Player X, name a TV show. Anyone who's seen it drinks 1",
                "Drink 1 if you've signed a petition this year",
                "Drink 1 if you like pineapple on pizza",
                "Drink 2 if you've ever tried to stream on Twitch",
                "Drink 1 if you don't want kids. Give out 2 if you do",
                "Player X, name a movie. Anyone who's seen it drinks 1",
                "Give 3 drinks if you've ever been arrested",
                "Give 2 drinks if you've hugged a dangerous animal (lion, tiger...)",
                "Drink 2 if you have more than 5 GCSEs (or equivalent)",
                "Player X, drink for each tattoo you have. None? Give out 2",
                "Drink 3 if you've slept with an ex. Double it if it's a friend's ex",
                "Drink if you're over 18 and still use Snapchat",
                "Drink 2 if you shared your Spotify Wrapped this year",
                "Player X, Player Y and Player Z, drink 3 if you skipped leg day this week",
                "Give out a drink for each night you've drunk in a row",
                "Drink 1 if you ever said 'No we can't!' to Bob the Builder",
                "Give 3 drinks if you've been thrown out of a venue",
                "Introverts drink 2",
                "Extroverts give out 2 drinks",
                "Drink 2 if you ever used Kik, for the emotional scars",
                "Player X, drink 1 for every TikTok you've been in (max 10)"
            )
        ),
        Category(
            name = "Action",
            colorRes = R.color.LightRed,
            defaultWeight = 18,
            info = "This is a task for whoever is named",
            prompts = listOf(
                "Player X, give advice to someone here without naming them. Refuse? Drink 2",
                "Player X, name your biggest turn-off or drink 3",
                "Player X, you control the music. Play a bad song and drink 1",
                "FREEZE! Player X, toss a coin. If it lands in a cup, they down it",
                "FREEZE! Whoever has the least left, finish your drink",
                "Least drunk player: the group decides how much you drink",
                "Player X, pick someone. Decide how much you both drink",
                "Player X, name something you've never done. Anyone who has, drinks",
                "Last to show a photo of another player on their phone drinks 4",
                "Player X, pick a word. Go round rhyming it — first to stall drinks 3",
                "Player X, pour a shot into someone's drink",
                "Player X, give someone a heartfelt compliment. The group decides if you drink 3",
                "Player X, two truths and a lie. If nobody spots the lie, they all drink 2",
                "Long arm pint! Player X, finish your drink without bending your elbow",
                "Everyone plays rock paper scissors with the person on your left. Overall winner gives out 5",
                "Player X, make a rousing speech. The group then decides how much you drink",
                "Player X, imitate Player Y — including their drinking",
                "Take a group selfie. Anyone who refuses drinks 3",
                "Hands on the table. Last to lift theirs gives out 5 sips",
                "Player X, take a shot like a hero or hand out two like a villain",
                "Player X, take one item of clothing from each player. Refuse? Drink 3",
                "First to recite the alphabet backwards gives out 5 drinks",
                "Phones in the middle. First to get a notification drinks 3",
                "Player X, let the person on your left draft a text from your phone. Don't send it? Drink 5",
                "Drink if you've ever drunk in a park, you menace",
                "'On my ship is...' Add an item and go round adding more. Break the list, drink 1 per item",
                "Silence! Drink in alphabetical order of names. Mess up and restart",
                "Player X, talk on one topic for a minute with no repeated words. Slip up? Drink",
                "Drink for every drug you've ever tried. We're judging you",
                "Player X, name an object in the room. Last to touch it drinks 3",
                "Player X, tell an embarrassing story or drink 3",
                "First to come up with an inspirational quote gives out 4 sips",
                "Player X, stand on one leg until told otherwise. Drop it and drink 1",
                "Player X, show off some athleticism (push-ups?) or drink 5",
                "Player X names a band. Player Y names 5 of their songs, or you both drink 5",
                "Player X, staring contest with someone. Loser drinks 3",
                "Player X, dare Player Y. Refuse and drink 4",
                "Player X, sing 30 seconds of karaoke or drink 2",
                "Stand up! Last player to do so drinks 2",
                "STOP! Player X, what did Player Y just say? Wrong and drink 2",
                "Hide and seek! Player X seeks. First found drinks 2, last found gives 2",
                "Player X, do a 30-second interpretive dance of whatever Player Y says",
                "Player X picks a word. Go round rhyming it — first to fail drinks 3",
                "Player X, sing your national anthem. Not passionate enough? Drink 3",
                "Player X hums a tune for 5 seconds. Player Y can't name it? Both drink 4",
                "On 3, hold up some fingers. Anyone matching another player drinks 2",
                "Player X, convince the group why you shouldn't drink 5 right now",
                "Player X, assign each eye colour 1, 2 or 3 drinks",
                "Player X, take 6 sips from your glass, or 1 from your bare palm",
                "Player X, refill your glass without using your hands",
                "Player X, invent a catchphrase to say every time you drink",
                "Player X, pick someone to do 20 push-ups",
                "Player X, pick someone to do 30 squats",
                "Bid for the right to give out 6 drinks. Bidding starts at 2",
                "Everyone, read out your last social media post. Refuse? Drink 2",
                "Go round naming bars and clubs you've been to. Stall and drink 2",
                "Player X, act out a movie scene in silence. First to guess it gives out 3",
                "Player X, tell a joke. If anyone laughs, they drink 2",
                "Player X, tell a story. The group decides if you drink 3",
                "Player X, pour a shot into two other players' drinks",
                "Player X, reveal your biggest phobia or take a shot",
                "Player X, pour Player Y's next drink",
                "On the next 20-minute mark, first to shout 'Pintley' gives out 5",
                "Couples, recall your last argument. Whoever was wrong drinks 5",
                "First to take off an item of clothing gives out 2 drinks",
                "Player X, eyes closed — name what everyone's drinking. 1 drink out per hit, drink your misses",
                "Player X, name African capitals. Give out 1 per correct answer, drink your mistakes",
                "Player X, name Asian capitals. Give out 1 per correct answer, drink your mistakes",
                "Player X, name South American capitals. Give out 1 per correct answer, drink your mistakes",
                "Player X, name an accessory. Anyone wearing one drinks 1",
                "Player X drinks for 5 seconds. Player Y counts",
                "Drink 1 if you're a summer person",
                "Drink 1 if you're a winter person",
                "Wearing a hat? Tip it at someone and they drink 2",
                "Lefties drink 1. Ambidextrous? Dual-wield two drinks and down both",
                "Everyone deliver a pickup line. Corniest one, and anyone who won't play, drinks 1",
                "Player X, do an impression of Player Y. The group gives out up to 3 drinks on quality",
                "Player X, tell us about the time you nearly shat yourself. Chicken out? Take a shot",
                "Player X, drink your body count (cap it at 10, we don't have all night)",
                "Player X, let someone edit your Tinder or take 2 shots. No Tinder? Give out a shot",
                "Player X, be Player Y's cheerleader every time they drink",
                "Player X, tell an offensive joke. Not offensive enough? Drink 4"
            )
        ),
        Category(
            name = "Rule",
            colorRes = R.color.Gold,
            defaultWeight = 4,
            info = "Rules affect everyone and stay in place until stated otherwise",
            prompts = listOf(
                "No eye contact. Catch someone's eye and you both drink 1",
                "On eye contact, first to wink makes the other drink 1",
                "Player X, rename everyone. Use the wrong name and drink 1",
                "Player X, ban a word and give it a replacement. Slip up and drink 1",
                "No crossing legs or touching hair. Caught? Drink 1",
                "Left-hand rule! Hold your drink with your non-dominant hand. Slip up and drink 1",
                "Everyone must call each player by a made-up name. Slip up and drink 1",
                "Player X, Player Y and Player Z are a team. The majority decides how they split drinks",
                "Everyone's Question Master. Answer anyone's question and drink 1",
                "Everyone swaps names. Use an old name and drink 1",
                "Whenever you drink, the person on your left or right drinks with you"
            )
        ),
        Category(
            name = "Weakness",
            colorRes = R.color.SicklyGreen,
            defaultWeight = 4,
            info = "This is a penalty that a single player holds until stated otherwise",
            prompts = listOf(
                "Player X, say anyone's name and you drink. They get to write their name on your skin",
                "Player X, call everyone by their full name. Fail and drink 1",
                "Player X, guard a small item. If anyone nabs it, drink 4",
                "Player X is the drinks bitch — make a drink for anyone who asks",
                "Player X, speak only in questions. Make a statement and drink 1",
                "Player X, no conjunctions (and, but, while...). Slip up and drink 1",
                "Player X, all your drinks are doubled. Sorry",
                "Player X, you may only drink using your index fingers. No spilling!",
                "Player X, swap drinks with Player Y",
                "Player X, you're an aristocrat — pinky up when you drink, or drink again",
                "Player X is on trial — only whisper to your lawyers (left and right) to speak",
                "Player X, keep up an impression of your choice. Break it and drink 2",
                "Player X, end every sentence with 'is that okay?!' or drink 1",
                "Player X, drink with your weaker hand. Slip up and drink 1",
                "Player X, raise your hand to speak. Forget and drink 1",
                "Player X, keep a straight face. Laugh or smile and drink 1",
                "Player X, speak only in outdated slang, ya dig",
                "Player X, say the opposite of what you mean",
                "Player X, speak only in Ye Olde English. Slip up and drink 1",
                "Player X, answer everything truthfully, as if you were Player Y"
            )
        ),
        Category(
            name = "Special",
            colorRes = R.color.Violet,
            defaultWeight = 3,
            info = "A player may use this once, whenever they want",
            prompts = listOf(
                "Player X, once, reflect a set of drinks back at whoever gives them to you",
                "Player X, pass one of your weaknesses to another player",
                "Player X, throw your hands up. Last to copy drinks 3",
                "Player X, thumb on the table. Last to copy drinks 3",
                "Player X, swap the name on any active card",
                "Player X, bring one retired rule back into play"
            )
        ),
        Category(
            name = "Wild",
            colorRes = R.color.ForestGreen,
            defaultWeight = 1,
            info = "These are up to you, have some fun",
            prompts = listOf(
                "Player X, decide what this card says",
                "Player X, ask the group a 'who's most likely' question",
                "Player X, invent a new rule"
            )
        ),
        Category(
            name = "Democracy",
            colorRes = R.color.LightBlue,
            defaultWeight = 13,
            info = "Everyone close your eyes and point to who you think it is. The minority drinks",
            prompts = listOf(
                "Who is the best dressed?",
                "Who is the worst driver?",
                "Who is the biggest lightweight?",
                "Who is the biggest alcoholic?",
                "Who here is the least drunk?",
                "Who here is the most fun?",
                "Who here is the strongest?",
                "Who will be the most successful in life?",
                "Who here is the most privileged?",
                "Who is the biggest social butterfly?",
                "Who would you rather be stranded on a desert island with?",
                "Who would you call to help hide a body?",
                "Who would you rather wake up as?",
                "Who would make the best politician?",
                "Who is the worst cook?",
                "Who is most likely to ditch plans last minute?",
                "Who is going to throw up first?",
                "Who is going to bed soonest?",
                "Who is worst at handling spice?",
                "Who is the least dominant?",
                "Who is the horniest?",
                "Who is wearing the most expensive clothes?",
                "Who is the most sensitive?",
                "Who has the worst taste in music?",
                "Who has the best taste in music?",
                "Who was the most popular at school?",
                "Who has the highest body count?",
                "Who has the weakest drink?",
                "Who has the strongest drink?",
                "Who is the most athletic?",
                "Who is the best gamer?",
                "Who has the strangest hobby?",
                "Who has the best taste in TV and film?",
                "Who is the least hygienic?",
                "Who is the worst loser?",
                "Who is the least employable?",
                "Who do you trust the most?",
                "Who would you want on your side in a fight?",
                "Who is most likely to complain?",
                "Who is the biggest bullshitter?",
                "Who is the most gullible?",
                "Who is the biggest nerd?",
                "Who is the best on a night out?",
                "Who is the most dramatic?",
                "Who is least likely to get into a club?",
                "Who is most likely to 'forget' to buy a round?",
                "Who would win in a fight, Player X or Player Y?",
                "Who is the loudest?",
                "Who is the most confrontational?",
                "Who has the hardest job?",
                "Who is the most persuasive?",
                "Who is the best tipper?",
                "Who is most likely to complain at a restaurant?",
                "Who is the most adventurous?",
                "Who would you least like to live with?",
                "Who is most likely to fall asleep first?",
                "Who is the worst in bed?",
                "Who would make the best warrior?",
                "Who would make the best king?",
                "Who is the most promiscuous?",
                "Who is the life of the party?",
                "Who would you want in a zombie apocalypse?",
                "Who would you want as a business partner?",
                "Who gives the best advice?",
                "Who gives the worst advice?",
                "Who knows the most about pop culture?",
                "Who is the most cultured?",
                "Who is the best at keeping a secret?",
                "Who is the biggest risk taker?",
                "Who is the most aggressive?",
                "Who will be the first to start a family?",
                "Who is the drunkest right now?",
                "Who would perform best in the military?",
                "Who is the most practical?",
                "Who is the coolest?",
                "Who is the group's main organiser?",
                "Who is your role model?",
                "Who would you want negotiating your release from a hostage situation?",
                "Who would you most want investigating your murder?",
                "Whose facts do you trust without checking?",
                "Who do you want beside you in a horror movie?",
                "Who is your chosen heist partner?",
                "Who is your chosen prison friend?",
                "Who would do best in prison?",
                "Who is most likely to be guilty of a crime?",
                "Who here will people write books about?",
                "Who is most likely to join an extremist group?",
                "Who is most likely to pull off a revolution?",
                "Who should really speak less?",
                "Who should really speak more?",
                "Who do you trust most to speak for you?",
                "Who do you trust least to speak for you?",
                "Who is the happiest right now?",
                "Who is the best storyteller?",
                "Who is the most passionate?",
                "Who do you trust least to plan a holiday?",
                "Who is always causing drama?",
                "Who is the most resilient?",
                "Who is the most optimistic?",
                "Who is the meanest?",
                "Who would make the best supervillain?",
                "Who has the best relationship with their parents?",
                "Who is the shot-caller?",
                "Who is the worst swimmer?",
                "Who is the parent of the group?",
                "Who would go furthest to help you?",
                "Who is the most elitist?"
            )
        ),
        Category(
            name = "Power",
            colorRes = R.color.CrimsonRed,
            defaultWeight = 3,
            info = "This is a benefit that a single player holds until stated otherwise",
            prompts = listOf(
                "Player X, pick a friend. Whenever you drink, they drink too",
                "Player X, you're the boss. Punish any 'workplace misconduct' with drinks",
                "Player X, everyone must ask before drinking. Forget and drink double",
                "Player X is a concerned father — everyone calls you 'daddy'. Slip up and drink 1",
                "Player X is Question Master. Answer their question and drink 1",
                "Player X is Passion Master — hand a drink to anyone lacking energy",
                "Player X, on your finger guns everyone freezes. Last to freeze drinks 2",
                "Player X is a cymbal monkey — on every clap, everyone (you too) drinks 1",
                "Player X, make someone laugh and they drink 1",
                "Player X is immune to all rules",
                "Player X is immune to the next 5 cards. Player Y drinks them instead"
            )
        ),
        Category(
            name = "Elimination",
            colorRes = R.color.Granite,
            defaultWeight = 2,
            info = "Remove something from play. Feel free to do this freely, not just on these cards",
            prompts = listOf(
                "All Rules are out of play",
                "All Powers are out of play",
                "All Weaknesses are out of play",
                "All Rules, Powers and Weaknesses are out of play"
            )
        ),
        Category(
            name = "Would You Rather",
            colorRes = R.color.Flamingo,
            defaultWeight = 5,
            info = "Everyone close your eyes. Thumbs up for option 1, thumbs down for option 2. The minority drinks",
            prompts = listOf(
                "Would you rather live agelessly for 100 years, or get a billion dollars?",
                "Would you rather breathe underwater, or survive any fall?",
                "Would you rather get a life sentence, or the death penalty?",
                "Would you rather only eat sweet food, or only spicy food?",
                "Would you rather live without social media, or without streaming?",
                "Would you rather have free travel forever, or a supercar?",
                "Would you rather be the richest person alive but hated, or broke but loved?",
                "Would you rather have street smarts, or book smarts?",
                "Would you rather have permanent summer, or permanent winter?",
                "Would you rather be reincarnated with your memories but no skills, or skills but no memories?",
                "Would you rather have immortality, or reincarnation with your memory intact?",
                "Would you rather eat the same meal forever, or only ever drink water?",
                "Would you rather lift cars but look weak, or look like a Greek god but be averagely strong?",
                "Would you rather have a million dollars, or a 50% shot at 20 million?",
                "Would you rather lose your hearing, or your sight?",
                "Would you rather die to save 10 strangers, or let them die and live?",
                "Would you rather have an amazing house, or amazing holidays?",
                "Would you rather cover for a cheating friend, or snitch on them?",
                "Would you rather be the strongest person alive, or the best at chess?",
                "Would you rather be a perfect artist, or a perfect mathematician?",
                "Would you rather have only one pet, or only one child?",
                "Would you rather have the hottest partner, or the smartest?",
                "Would you rather enter witness protection and never see your family, or have 100 kids right now?",
                "Would you rather control water, or fire?",
                "Would you rather be permanently bald, or have werewolf hair growth?",
                "Would you rather only watch movies, or only listen to them?",
                "Would you rather always be an hour late, or two hours early?",
                "Would you rather read people's thoughts, or their memories?",
                "Would you rather never hear new music, or never replay old music?",
                "Would you rather find true love but never work, or have a great career but never find love?",
                "Would you rather live in the Sahara, or Antarctica?",
                "Would you rather code like a genius, or play an instrument like one?",
                "Would you rather be ghosted by your crush, or told outright they're not into you?",
                "Would you rather be unable to shower, or unable to brush your teeth?",
                "Would you rather know how you'll die, or when?",
                "Would you rather have a personal chef, or a personal driver?",
                "Would you rather have two extra arms, or a third eye?",
                "Would you rather never break anything, or never lose anything?",
                "Would you rather be smart but relied on by everyone, or clueless but completely looked after?",
                "Would you rather choose where you go for dinner, or let someone else?",
                "Would you rather have a great memory, or be a comedic genius?",
                "Would you rather date someone similar to you, or your opposite?",
                "Would you rather a world without war, or without poverty?",
                "Would you rather live underwater, or in space?",
                "Would you rather never need sleep, or never get sick?",
                "Would you rather talk to animals, or speak every language fluently?",
                "Would you rather move objects with your mind, or have super speed?",
                "Would you rather be immune to alcohol, or to recreational drugs?",
                "Would you rather have everyone respect you, or desire you?",
                "Would you rather be a dog, or a cat?",
                "Would you rather have a photographic memory, or forget anything at will?",
                "Would you rather win the lottery, or find true love?",
                "Would you rather be a lightweight, or a heavyweight drinker?",
                "Would you rather a world ruled by passion, or by logic?",
                "Would you rather own a 5-star hotel, or a 3-Michelin-star restaurant?",
                "Would you rather swim 10 metres through 50°C water, or crawl 10 metres over hot coals?",
                "Would you rather be the best fighter in the world, or the fastest reader?",
                "Would you rather sleep with Player X, or Player Y?",
                "Would you rather earn double, or work half as much for the same pay?",
                "Would you rather live now as a regular person, or 100 years ago as royalty?",
                "Would you rather be known as a prostitute, or a fraudster who targets the elderly?",
                "Would you rather start a business empire with Player X, or Player Y?",
                "Would you rather be Prime Minister, or their most trusted advisor?",
                "Would you rather travel 40 years into the past, or the future?",
                "Would you rather have sex in the shower, or the back of a car?",
                "Would you rather kill one person to save three, or spare them and let three die?",
                "Would you rather be wrongly believed to have cheated, or cheat and get away with it?",
                "Would you rather be addicted to cocaine, or to gambling?",
                "Would you rather fight like Mike Tyson, or Bruce Lee?",
                "Would you rather serve in Heaven, or rule in Hell?"
            )
        ),
        Category(
            name = "Ultra Challenge",
            colorRes = R.color.UltraDark,
            defaultWeight = 1,
            isUltra = true,
            info = "The rarest card of all. Two players go head to head — the loser downs their drink",
            prompts = listOf(
                "Player X and Player Y, sing a duet of a song the group picks. Group votes for the best — loser downs their drink",
                "Player X and Player Y, hold an invisible chair against the wall. First to drop downs a full drink",
                "Player X and Player Y, make competing toasts on a subject the group picks. Group votes — loser downs their drink"
            )
        )
    )
}
